export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
export const SET_DONE_FILTER = 'SET_DONE_FILTER';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';

export const SET_EDIT_MODE = 'SET_EDIT_MODE';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const RENAME_CATEGORY = 'RENAME_CATEGORY';
export const CHOOSE_CATEGORY = 'CHOOSE_CATEGORY';
export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';

export const ADD_TASK = 'ADD_TASK';
export const TOGGLE_TASK = 'TOGGLE_TASK';
